### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fjc0k** [fjc0k/yapi-to-typescript#1]
- [x] additionalProperties 设为 false
- [x] data 接口为 any 时，将其设为可选
- [x] 优化 dataKey 支持
- [x] 设计并暴露 File 适配类
- [x] 命令行创建配置文件
